SELECT I.ID, N.FISH_NAME, I.LENGTH 
FROM FISH_INFO I
    INNER JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH =
    (
        SELECT MAX(I.LENGTH)
        FROM FISH_INFO I
        WHERE I.FISH_TYPE = N.FISH_TYPE
    )
ORDER BY I.ID;